# my global config
global:
  scrape_interval:     5s
  evaluation_interval: 1s
  # scrape_timeout is set to the global default (10s).

  external_labels:
    demo:     true

rule_files:
- "time.rules"

scrape_configs:
- job_name: prometheus
  scheme: http

  static_configs:
  - targets: ['localhost:9090']


